[package]
name = "engineio"
version = "0.1.0"
edition = "2021"
description = "An implementation of a engineio written in rust."
repository = "https://github.com/socket-iox/socket-io"
keywords = ["socketio", "engineio", "network", "protocol"]
categories = [
  "network-programming",
  "web-programming",
  "web-programming::websocket",
  "web-programming::socketio",
]
license = "MIT"


[dependencies]
base64 = "0.13.0"
bytes = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
thiserror = "1.0"

[lib]
